### ISSUE TITLE
第二个作业cnn.py关于三层卷积神经网络的第二层权值初始化有疑问

### ISSUE THREAD

**Issue by qianjinhao** [sharedeeply/cs231n-camp#4]
第二个作业 中cnn.py 里面 权重的初始化部分：
self.params['W2'] = np.random.normal(0, weight_scale, size=(num_filters * h // 2 * w // 2, hidden_dim))
为什么是num_filters * h // 2 * w // 2？
这个参数不是应该跟filters的大小有关吗，为什么是跟h和w有关？

**Comment by L1aoXingyu** [comment]
w2 是全连接层的weight
